[workspace]
name = "CLAM"
version = "0.1.0"
description = "CLAM Website"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[dependencies]
python = ">=3.10"
mkdocs = ">=1.6.1"
pydantic = ">=2.12.1"
pyyaml = ">=6.0.1"

# mkdocs
mkdocs-material = ">=9.5.50"
mkdocs-macros-plugin = ">=1.3.7"
mkdocs-jupyter = ">=0.25.1"
pillow = "*"
cairosvg = "*"
